ALTER TABLE LINIEDOCUMENT DROP CONSTRAINT FK_LINIEDOCUMENT_DOCUMENT_id
ALTER TABLE LINIEDOCUMENT DROP CONSTRAINT FK_LINIEDOCUMENT_MIJLOCFIX_id
ALTER TABLE MIJLOCFIX DROP CONSTRAINT FK_MIJLOCFIX_GESTIUNE_id
ALTER TABLE Transfer DROP CONSTRAINT FK_Transfer_GESTIUNESURSA_id
ALTER TABLE Transfer DROP CONSTRAINT FK_Transfer_GESTIUNEDESTINATIE_id
DROP TABLE Document CASCADE
DROP TABLE GESTIUNE CASCADE
DROP TABLE LINIEDOCUMENT CASCADE
DROP TABLE MIJLOCFIX CASCADE
DROP TABLE Transfer CASCADE
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
