ALTER TABLE LinieDocument DROP CONSTRAINT FK_LinieDocument_MIJLOCFIX_id
ALTER TABLE LinieDocument DROP CONSTRAINT FK_LinieDocument_DOCUMENT_id
ALTER TABLE Transfer DROP CONSTRAINT FK_Transfer_GESTIUNESURSA_id
ALTER TABLE Transfer DROP CONSTRAINT FK_Transfer_GESTIUNEDESTINATIE_id
DROP TABLE Document CASCADE
DROP TABLE GESTIUNE CASCADE
DROP TABLE LinieDocument CASCADE
DROP TABLE MIJLOCFIX CASCADE
DROP TABLE Transfer CASCADE
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
